# Generated by Django 5.0.3 on 2024-04-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_tag_options_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=300, unique=True),
        ),
    ]
