# Generated by Django 5.0.3 on 2024-04-18 20:16

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=django_quill.fields.QuillField(),
        ),
    ]
