# Generated by Django 5.0.3 on 2024-04-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="reading_time",
            field=models.IntegerField(default=0),
        ),
    ]
