# Generated by Django 5.0.3 on 2024-05-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_reading_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="tag_icons/"),
        ),
    ]
