# Generated by Django 5.0.3 on 2024-05-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_tag_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="reading_time",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
